### PR TITLE
Improve publishing process with prepare script and npmignore

### PR DESCRIPTION
**Pull request by arjunmehta**
### npm prepare script
Adds an npm `prepare` script which will run before publishing. No longer duplicates all files and uses the original package files as before.

Instead the prepare script (`prepublish-build`):
- Creates a `dist` directory
- Builds the frontend `homebridge-ui`
- Copies the build to the `dist` directory

This `dist` directory has the built homebridge-ui files, and the `config.schema.json` points to it as the UI source.

### include only built files in npm publish

- `lib/homebridge-ui` added to the `.npmignore` file to prevent unnecessary distribution of source files

## Testing

Simply run `npm pack` locally and see the output in the created tarball.

### CODE REVIEW

**Comment by arjunmehta** [comment]
@jgrimard Ready for review/merge into your PR

**Comment by jgrimard** [comment]
Hi @arjunmehta,
Is it working for you?  I'm getting the below error when trying to navigate to the config / login screen.

```
[9/19/2021, 12:51:36 PM] [Homebridge UI] [@jgrimard/homebridge-vivint-test1] internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '../vivint_mfa'
Require stack:
- /usr/lib/node_modules/@jgrimard/homebridge-vivint-test1/dist/homebridge-ui/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/lib/node_modules/@jgrimard/homebridge-vivint-test1/dist/homebridge-ui/server.js:14:22)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/@jgrimard/homebridge-vivint-test1/dist/homebridge-ui/server.js'
  ]
}
```
I think it is this line:
https://github.com/arjunmehta/homebridge-vivint/blob/d9d3cbd249364a7429b058f6d91c248fd47901f6/lib/homebridge-ui/server.js#L14

**Review by jgrimard — COMMENTED** [review]
@arjunmehta Great job with the build script. Thank you for doing that.

**Comment by arjunmehta** [comment]
@jgrimard Ah sorry about the error, I was worried there might have been reference errors. Glad you checked! Thanks for merging!

**Pull request merged**
